const WEB_3_AUTH_ID = process.env.NEXT_PUBLIC_WEB_3_AUTH_ID || ''
const OAUTH_ID = process.env.NEXT_PUBLIC_OAUTH_ID || ''
const WEB_3_STORAGE_API_TOKEN =
  process.env.NEXT_PUBLIC_WEB_3_STORAGE_API_TOKEN || ''
const MONGO_URI = process.env.NEXT_PUBLIC_MONGO_URI || ''

export { WEB_3_AUTH_ID, OAUTH_ID, WEB_3_STORAGE_API_TOKEN, MONGO_URI }
