/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface ITokensFactoryInterface extends utils.Interface {
  functions: {
    "deployNextFutureYieldToken(uint256)": FunctionFragment;
    "deployPT(string,uint256,string,uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "deployNextFutureYieldToken" | "deployPT"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "deployNextFutureYieldToken",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "deployPT",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "deployNextFutureYieldToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deployPT", data: BytesLike): Result;

  events: {};
}

export interface ITokensFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ITokensFactoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    deployNextFutureYieldToken(
      nextPeriodIndex: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    deployPT(
      _ibtSymbol: PromiseOrValue<string>,
      _ibtDecimals: PromiseOrValue<BigNumberish>,
      _platformName: PromiseOrValue<string>,
      _perioDuration: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  deployNextFutureYieldToken(
    nextPeriodIndex: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  deployPT(
    _ibtSymbol: PromiseOrValue<string>,
    _ibtDecimals: PromiseOrValue<BigNumberish>,
    _platformName: PromiseOrValue<string>,
    _perioDuration: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    deployNextFutureYieldToken(
      nextPeriodIndex: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    deployPT(
      _ibtSymbol: PromiseOrValue<string>,
      _ibtDecimals: PromiseOrValue<BigNumberish>,
      _platformName: PromiseOrValue<string>,
      _perioDuration: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    deployNextFutureYieldToken(
      nextPeriodIndex: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    deployPT(
      _ibtSymbol: PromiseOrValue<string>,
      _ibtDecimals: PromiseOrValue<BigNumberish>,
      _platformName: PromiseOrValue<string>,
      _perioDuration: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    deployNextFutureYieldToken(
      nextPeriodIndex: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    deployPT(
      _ibtSymbol: PromiseOrValue<string>,
      _ibtDecimals: PromiseOrValue<BigNumberish>,
      _platformName: PromiseOrValue<string>,
      _perioDuration: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
