/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ITokensFactory,
  ITokensFactoryInterface,
} from "../../../contracts/apwine/ITokensFactory";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "nextPeriodIndex",
        type: "uint256",
      },
    ],
    name: "deployNextFutureYieldToken",
    outputs: [
      {
        internalType: "address",
        name: "newToken",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "_ibtSymbol",
        type: "string",
      },
      {
        internalType: "uint256",
        name: "_ibtDecimals",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "_platformName",
        type: "string",
      },
      {
        internalType: "uint256",
        name: "_perioDuration",
        type: "uint256",
      },
    ],
    name: "deployPT",
    outputs: [
      {
        internalType: "address",
        name: "newToken",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ITokensFactory__factory {
  static readonly abi = _abi;
  static createInterface(): ITokensFactoryInterface {
    return new utils.Interface(_abi) as ITokensFactoryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITokensFactory {
    return new Contract(address, _abi, signerOrProvider) as ITokensFactory;
  }
}
